[build]
  publish = "."

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

[[redirects]]
  from = "/app"
  to = "/app.html"
  status = 200

[[redirects]]
  from = "/onboarding"
  to = "/onboarding.html"
  status = 200

[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, max-age=604800, immutable"
